### ISSUE TITLE
prewas specifying reference genome 

### ISSUE THREAD

**Issue by hsinjou0714** [Snitkin-Lab-Umich/prewas#9]
When I read into to the guid of prewas, I saw that reference genome could be provided, but couldn't see how to specify my reference genome in the input of prewas:
results_maximal = prewas(dna = vcf, 
                         tree = tree, 
                         outgroup = outgroup, 
                         gff = gff,
                         anc = TRUE)
How do I specify this? Is the genome detected in the vcf input file? 
Thank you

**Comment by katiesaund** [comment]
The reference genome information is implied in the VCF file, as variants are called against the reference genome's sequence. No need to specify anything in the prewas function. In the example you've given here, prewas will return the ancestral allele.
